server:
  port: 8081
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: test
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
jwt:
  secret: test
  expiration: 6000
  header: X-Auth-Token
swagger:
  enabled: true