server:
  port: 8080
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: mysql
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: test
  rabbitmq:
    addresses: xxx
  cloud:
    stream:
      bindings:
        output:
          destination: mail
          group: mail-group
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
jwt:
  secret: test
  expiration: 6000
  header: X-Auth-Token
swagger:
  enabled: true